### ISSUE TITLE
2D cases

### ISSUE THREAD

**Issue by kingnobro** [OllieBoyne/pytorch-arap#2]
I am trying to modify [puppet-warp](https://github.com/mikecokina/puppet-warp) (ARAP for shape manipulation, 2D) into pytorch version. However, I find that `numpy.linalg.lstsq` (puppet-warp code) and `torch.linalg.lstsq` (after my modification) output different results, and numpy is more accurate. I don't know how to solve it.

Then I find this repository. Can this 3D ARAP seamlessly be applied to 2D cases? I also notice you use `torch.lstsq` in code, which is deprecated after pytorch version 1.9. Should I use pytorch 1.9?

**Comment by OllieBoyne** [comment]
Hi,

A 2D implementation should work, but where faces are used in the implementation, you would use edges instead. [See the original paper here for more details](https://igl.ethz.ch/projects/ARAP/arap_web.pdf). This is quite substantially different to the code used in this repository, so you would need to make some significant changes to the 'mesh' representation to work in 2D.

Regarding `torch.lstsq`, this was originally made for PyTorch <= 1.9, so you should use that for compatibility. If you are able to rewrite the code for PyTorch >= 1.9, feel free to make a pull request with the changes!

**Comment by kingnobro** [comment]
Thanks for you reply.

I found the reason why `lstsq` outputs different results. That is [numerical accuracy](https://pytorch.org/docs/stable/notes/numerical_accuracy.html#linear-algebra-torch-linalg). In numpy, the input `float32` may be automatically converted into `float64` during computation, but in `pytorch`, I think we need to do this operation manually.
